######################################################################
# Automatically generated by qmake (3.0) mar. juin 2 13:32:41 2015
######################################################################

QT+=widgets testlib
TEMPLATE = app
TARGET = redshiftconf
INCLUDEPATH += .

# Input
HEADERS += redshiftconf.h sicon.h
FORMS += redshiftconf.ui
SOURCES += main.cpp redshiftconf.cpp sicon.cpp
